-- Kullanıcı kaynak kolonları ekleme (idempotent)
ALTER TABLE users ADD COLUMN money INTEGER NOT NULL DEFAULT 50;
ALTER TABLE users ADD COLUMN wood INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN grain INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN business INTEGER NOT NULL DEFAULT 0;
