tunnel: 961f2bba-1f4b-43f4-af3c-a3dbbced3f7e
credentials-file: /etc/cloudflared/961f2bba-1f4b-43f4-af3c-a3dbbced3f7e.json
ingress:
  - hostname: tcrtsmlatronline.app
    service: http://nginx:80
  - hostname: www.tcrtsmlatronline.app
    service: http://nginx:80
  - hostname: admin.tcrtsmlatronline.app
    service: http://nginx:80
  - service: http_status:404
# metrics: 0.0.0.0: metrics endpoint gerekirse açılabilir
