name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add known_hosts
        run: |
          ssh-keyscan -H 192.168.1.106 >> ~/.ssh/known_hosts

      - name: Sync files
        run: |
          rsync -avz --delete --exclude '.git' ./ musa@192.168.1.106:/home/musa/oyun/

      - name: Install & Migrate
        run: |
          ssh musa@192.168.1.106 'cd /home/musa/oyun/server && npm install --omit=dev && npm run migrate'

      - name: Restart service
        run: |
          ssh musa@192.168.1.106 'sudo systemctl restart oyun'
