name: Deploy to Server

on:
  push:
    branches: [ "main" ]   # PR'da secrets geçmez; main'e push çalışır
  workflow_dispatch: {}     # Elle tetiklemek için

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout (metadata only)
        uses: actions/checkout@v4

      - name: ✅ Sanity check secrets
        run: |
          [[ -n "${{ secrets.SERVER_HOST }}" ]] || (echo "❌ Missing SERVER_HOST" && exit 1)
          [[ -n "${{ secrets.SERVER_USER }}" ]] || (echo "❌ Missing SERVER_USER" && exit 1)
          [[ -n "${{ secrets.SERVER_SSH_KEY }}" ]] || (echo "❌ Missing SERVER_SSH_KEY" && exit 1)
          echo "✅ Secrets look set."

      - name: 🔐 SSH to Server and Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            bash /opt/gameby/deploy.sh
