name: Deploy (Self-hosted) [DISABLED]

on:
  workflow_dispatch:
    inputs:
      disabled:
        description: 'This workflow is disabled. Use SSH deploy.'
        required: false
        default: 'true'

concurrency:
  group: deploy-selfhosted-main
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Self-hosted deploy workflow is disabled. Use Deploy to Server (deploy.yml)."

      - name: Write .env for compose
        working-directory: ${{ github.workspace }}
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CURSOR_SECRET: ${{ secrets.CURSOR_SECRET }}
          CURSOR_SECRET_ROTATION: ${{ secrets.CURSOR_SECRET_ROTATION }}
          REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
          AGENT_ENABLED: ${{ secrets.AGENT_ENABLED }}
          AGENT_CONFIG_PATH: ${{ secrets.AGENT_CONFIG_PATH }}
        run: |
          set -euo pipefail
          umask 077
          cat > .env << EOF
          JWT_SECRET=${JWT_SECRET}
          CURSOR_SECRET=${CURSOR_SECRET}
          CURSOR_SECRET_ROTATION=${CURSOR_SECRET_ROTATION}
          REFRESH_SECRET=${REFRESH_SECRET}
          CORS_ORIGIN=${CORS_ORIGIN}
          BASIC_AUTH_USER=${BASIC_AUTH_USER}
          BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
          AGENT_ENABLED=${AGENT_ENABLED}
          AGENT_CONFIG_PATH=${AGENT_CONFIG_PATH}
          EOF

      - name: Compose up
        working-directory: ${{ github.workspace }}
        env:
          COMPOSE_PROJECT_NAME: gameby
        run: |
          set -euo pipefail
          if id -nG | grep -q '\bdocker\b'; then
            SUDO=""
          elif sudo -n true 2>/dev/null; then
            SUDO="sudo"
          else
            echo "Runner user is not in 'docker' group and passwordless sudo is not available." >&2
            echo "Add the runner to docker group or enable NOPASSWD sudo for docker." >&2
            exit 1
          fi
          if docker compose version >/dev/null 2>&1; then
            DC="docker compose"
          elif command -v docker-compose >/dev/null 2>&1; then
            DC="docker-compose"
          else
            echo "docker compose not available on runner"; exit 1
          fi
          $SUDO $DC down --remove-orphans || true
          $SUDO $DC up -d --build

      - name: Health check
        working-directory: ${{ github.workspace }}
        env:
          COMPOSE_PROJECT_NAME: gameby
        run: |
          set -euo pipefail
          if id -nG | grep -q '\bdocker\b'; then
            SUDO=""
          elif sudo -n true 2>/dev/null; then
            SUDO="sudo"
          else
            SUDO=""
          fi
          for i in {1..30}; do
            curl -fsS http://127.0.0.1/health && break || true
            sleep 2
          done
          if ! curl -fsS http://127.0.0.1/health; then
            if docker compose version >/dev/null 2>&1; then
              $SUDO docker compose ps || true
            elif command -v docker-compose >/dev/null 2>&1; then
              $SUDO docker-compose ps || true
            fi
            exit 1
          fi
