name: Runner CI (smoke)

on:
  push:
    branches: [ feat/runner-setup ]
  pull_request:
    branches: [ feat/runner-setup ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Unit smoke (cursor security)
        run: npm --prefix apps/api/src run test:unit:cursor-security

      - name: Coverage (full)
        run: npm --prefix apps/api/src run coverage:full

      - name: Upload coverage artefacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-logs
          path: |
            apps/api/src/coverage/
            logs/
