name: sweep-report
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate sweep report
        run: node scripts/sweep.mjs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sweep-report
          path: artifacts/sweep-report.json
